import type { NextPage } from "next";
import Head from "next/head";
import Pilgrims from "../components/pilgrims";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Test of Pilgrims</h1>
        <Pilgrims />
      </div>
    </div>
  );
};

export default Home;
